version: '3.4'

services:
  carstoreweb:
    image: ${DOCKER_REGISTRY-}carstoreweb
    build:
      context: .
      dockerfile: CarStoreWeb/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - PurchaseApi=http://carstorepurchase/
      - InventoryApi=http://carstoreinventory/
      - CartApi=http://carstorecart/
    ports:
      - 5001:80
      - 5051:443
    command: printenv
    depends_on: 
      - carstorepurchase
      - carstorecart
      - carstoreinventory

  carstorepurchase:
    image: ${DOCKER_REGISTRY-}carstorepurchase
    build:
      context: .
      dockerfile: CarStorePurchase/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - InventoryApi="http://carstoreinventory/"
      - CartApi="http://carstorecart/"
    ports:
      - 5002:80
      - 5052:443

  carstoreinventory:
    image: ${DOCKER_REGISTRY-}carstoreinventory
    build:
      context: .
      dockerfile: CarStoreInventory/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5003:80
      - 5053:443

  carstorecart:
    image: ${DOCKER_REGISTRY-}carstorecart
    build:
      context: .
      dockerfile: CarStoreCart/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5004:80
      - 5054:443
