version: '3.4'

services:
  carstoreweb:
    image: ${DOCKER_REGISTRY-}carstoreweb
    build:
      context: .
      dockerfile: CarStoreWeb/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - PurchaseApi="http://localhost:5002"
      - InventoryApi="http://localhost:5003"
      - CartApi="http://localhost:5004"
    ports:
      - 5001:80
      - 5051:443
    depends_on: 
      - carstorepurchase
      - carstorecart
      - carstoreinventory

  carstorepurchase:
    image: ${DOCKER_REGISTRY-}carstorepurchase
    build:
      context: .
      dockerfile: CarStorePurchase/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - InventoryApi="http://localhost:5003"
      - CartApi="http://localhost:5004"
    ports:
      - 5002:80
      - 5052:443

  carstoreinventory:
    image: ${DOCKER_REGISTRY-}carstoreinventory
    build:
      context: .
      dockerfile: CarStoreInventory/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5003:80
      - 5053:443

  carstorecart:
    image: ${DOCKER_REGISTRY-}carstorecart
    build:
      context: .
      dockerfile: CarStoreCart/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5004:80
      - 5054:443
